// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String calculateMahjongFromCamera({
  required List<int> tiles,
  required List<int> doraIndicators,
  required double lastTileAngle,
  required double lastTileDistance,
  required bool isRiichi,
  required bool isIppatsu,
  required bool isHaitei,
  required bool isHoutei,
  required bool isChankan,
  required String prevalentWind,
  required String seatWind,
  required int honba,
  required String overrideHand,
  required String overrideDora,
}) => RustLib.instance.api.crateApiSimpleCalculateMahjongFromCamera(
  tiles: tiles,
  doraIndicators: doraIndicators,
  lastTileAngle: lastTileAngle,
  lastTileDistance: lastTileDistance,
  isRiichi: isRiichi,
  isIppatsu: isIppatsu,
  isHaitei: isHaitei,
  isHoutei: isHoutei,
  isChankan: isChankan,
  prevalentWind: prevalentWind,
  seatWind: seatWind,
  honba: honba,
  overrideHand: overrideHand,
  overrideDora: overrideDora,
);

String calculateShantenAndWait({
  required List<int> tiles,
  required String overrideHand,
}) => RustLib.instance.api.crateApiSimpleCalculateShantenAndWait(
  tiles: tiles,
  overrideHand: overrideHand,
);

Float32List convertYuvToRgbTensor({
  required List<int> yBytes,
  required List<int> uBytes,
  required List<int> vBytes,
  required int yRowStride,
  required int uvRowStride,
  required int uvPixelStride,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiSimpleConvertYuvToRgbTensor(
  yBytes: yBytes,
  uBytes: uBytes,
  vBytes: vBytes,
  yRowStride: yRowStride,
  uvRowStride: uvRowStride,
  uvPixelStride: uvPixelStride,
  width: width,
  height: height,
);
